### ISSUE TITLE
Not Working, Does this work in Python3

### ISSUE THREAD

**Issue by ghost** [msztolcman/hashfile#1]
`hashfile file.zip`
`hashfile -x file.zip`

**Comment by msztolcman** [comment]
`hashfile` doesn't recognize `-x` argument, what it should do? Neither md5sum nor shasum doesn't recognize it too.

And normal call, `hashfile path` works fine on both, Py2 and Py3. What is your output? Have you any error message?

**Comment by msztolcman** [comment]
@webscent OK, I found issue with reading binary data from STDIN, fixed in 2.1.5 (already in PyPI).

**Comment by ghost** [comment]
Great
